repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: check-added-large-files
    - id: check-json
    - id: check-merge-conflict
    - id: check-yaml
    - id: end-of-file-fixer
    - id: pretty-format-json
      args:
        - --autofix
    - id: trailing-whitespace

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    - id: isort
      args:
      - --profile
      - black

  - repo: https://github.com/ambv/black
    rev: 22.1.0
    hooks:
    - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.941
    hooks:
    - id: mypy

  - repo: local
    hooks:
    - id: flake8
      name: flake8
      entry: poetry run flake8
      language: system
      types: [python]
    - id: pytest
      name: pytest
      language: system
      entry: poetry run pytest --cov=python_project
      types: [python]
